//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfterSalesDBEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cataloghi
    {
        public int IdCatalogo { get; set; }
        public string PrefissoNome { get; set; }
        public int SuffissoNome { get; set; }
        public string Anno { get; set; }
        public string Versione { get; set; }
        public int IdEstensione { get; set; }
        public int IdCostruttore { get; set; }
        public string Pdf { get; set; }
        public Nullable<int> IdUtenteProprietario { get; set; }
        public Nullable<System.DateTime> DataChiusura { get; set; }
        public Nullable<int> IdUtenteChiusura { get; set; }
        public System.DateTime DataInserimento { get; set; }
        public int IdUtenteInserimento { get; set; }
        public string Note { get; set; }
        public Nullable<int> IdPeriodoFatturazione { get; set; }
        public byte Eliminato { get; set; }
    }
}
